headersOrigin = "inline"
redirectsOrigin = "inline"
functionsDirectory = "C:\\Users\\User\\Desktop\\FakeStake-main\\.netlify\\functions-internal"
functionsDirectoryOrigin = "config"

[dev]
framework = "next"

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "C:\\Users\\User\\Desktop\\FakeStake-main\\.next"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\Users\\User\\Desktop\\FakeStake-main"
command = "npm run build"
functions = "C:\\Users\\User\\Desktop\\FakeStake-main\\.netlify\\functions-internal"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]